#! /bin/bash
### BEGIN INIT INFO
# Provides:          Storage
# Required-Start:    $remote_fs $network
# Required-Stop:     $remote_fs $network
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Description:       Storage
### END INIT INFO
loop_dev=`sh /opt/setup_storage/losetup.sh`
